### ISSUE TITLE
Refactor grammars

### ISSUE THREAD

**Issue by vonwenckstern** [MontiSim/SimulationLanguage#20]
Your grammars are very like Antlr4 grammars.

Let's take an example at:
```
symbol scope Simulation = "sim" Name "{"
    ((SimulationRenderFrequency|
    SimulationLoopFrequency|
    SimulationDuration|
    SimulationType|
    Weather|
    Time|
    MapPath|
    MapName|
    MapHeight|
    MapOverlap|
    MapSectorWidth|
    MapSectorHeight|
    MaxSectorUsers|
    Timeout|
    Gravity|
    Pedestrians|
    PedestrianDensity|
    Vehicles|
    Channel) ";")*
  "}";

  SimulationRenderFrequency = "sim_render_frequency" AlternativeInput;
  SimulationLoopFrequency = "sim_loop_frequency" AlternativeInput;
  SimulationDuration = "sim_duration" AlternativeInput;
  SimulationType = "sim_type" simType:["fixed"|"realtime"|"maxfps"] ;
```

It would be better to use the powerful MontiCore features:
```
interface SimulationProperty;

symbol scope Simulation = "sim" Name "{"
   SimulationProperty*
"}";

SimulationRenderFrequency implements SimulationProperty = "sim_render_frequency" AlternativeInput ";";
SimulationLoopFrequency  implements SimulationProperty = "sim_loop_frequency" AlternativeInput ";";
SimulationDuration  implements SimulationProperty = "sim_duration" AlternativeInput ";";
SimulationType  implements SimulationProperty = "sim_type" simType:["fixed"|"realtime"|"maxfps"] ";";
```

This would also allow to extend the grammar later and add new `SimulationProperty` rules.

**Comment by vonwenckstern** [comment]
Here is the link to the MontiCore reference manual (there you can take a look at `interface` rules in grammars):
http://monticore.de/MontiCore_Reference-Manual.2017.pdf

**Comment by vonwenckstern** [comment]
@DeltaBoss You do not access them directly, since this would mean you use `instanceof` and we do not do it. The reason why is that if you add a new rule late which also implements this interface, than you need to modify the code where your `instanceof` is. Instead we use the visitor Pattern (to emulate double dispatching). In the ref-man are examples for the visitor pattern.

**Comment by DeltaBoss** [comment]
Yes, the simulation scope therefore is not the problem, but the scope hierarchy is flat in my case, meaning I could not do the same for weather and channel, because in those cases the stc only works on the these nodes and accessed the sub nodes from there. 
On second thought regarding the simulation scope: The cardinality cocos check the different list sizes to deny more than 1 entry of each setting. Would I then instead need to have the coco run a visitor which counts the number of settings nodes instead?

**Comment by DeltaBoss** [comment]
stc aside; why do I perform coco checks after creating the st, when I can just as well perform a check on the AST first and skip the st creation entirely of something is wrong

**Comment by vonwenckstern** [comment]
since for some ContextConditions (e.g. checking the type of a variable - which is in the AST only a String - you need to know how the variable was defined, and for that you need the symbol table).

Example:
```
int i = 8;
List l = ...;
int d = l + i; // how do you want to perform a CoCo check here only on the AST, you need to resolve l and i, and therefore you need the symbol table
```

Even if you do not need the symbol table yet, you still should keep the order of doing the CoCo check after creating the symbol table; otherwise it will crash when anybody extends your language.

**Comment by DeltaBoss** [comment]
The AST already contains all user input; it is just a matter of navigating through it. Utilizing solely the AST makes the CoCo infrastructure completely unbound from the ST, which I thought would be rather desirable coupling-wise as well as (in error-case) also skipping ST creation entirely and thus also being more efficient. After looking at the javaDSL CoCos, I understand though, why it would lead to crashes. I guess since offering conventional post-STC CoCos as well as clever pre-STC CoCos would get rejected, I'll have to rewrite all CoCos entirely...

Back to the STC though:
Lets create a small example: 
`RULE1 = { (RULE2|RULE3|RULE4)* }` where RULE2-4 appear once.
I have a class which models RULE1 by containing RULE2-4 and has it's own symbol, kind and resolvingfilter. The STC only visits RULE1 nodes, simply grabs the data from the sub-nodes and creates a symbol holding the RULE1 class. This is simple to create and access. 
If I were to now introduce a grammar side interface for RULE2-4, I would need to create symbol, kind and resolvingfilters for those 3 rules as well, turn RULE1 into a scope-spanning-symbol and build a nested scope and create the RULE1 object on leaving the node. This would result in 9 more files needing to be implemented and the STC becoming slightly less efficient since it needs to work on all subnodes now as well. 
Overall I have trouble seeing how this would be a good trade-off considering it would only save a line in the grammar?
